# Generated by Django 5.0.4 on 2024-05-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_ticket_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Categorie',
            new_name='Urgent',
        ),
    ]
