# Generated by Django 5.2.6 on 2026-09-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_rename_categorie_ticket_urgent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-Date', '-id']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Solved', 'Solved'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
